### ISSUE TITLE
Change  'Feels... what' to 'Feels Impossible'

### ISSUE THREAD

**Issue by GeneralContactUnit** [fantasycalendar/kobold-plus-fight-club#10]
The new feature to add difficulty levels above deadly is a good one.

However, the final option on the list may be confusing to new users and does not really communicate the "ludicrous" difficulty well.

I suggest you change "Feels.. what" to "Feels Impossible" to better communicate the difficulty of this level of encounter.

**Comment by Haxxer** [comment]
Changed in recent updates
