### ISSUE TITLE
On Firefox, the Encounter Generator doesn't use the party size/levels

### ISSUE THREAD

**Issue by rrichardson** [fantasycalendar/kobold-plus-fight-club#15]
I tried this with both a Generic Party and a Detailed party.  In both cases,  I get an encounter generated for a party of a single level 1 PC. 

On Chrome, everything works perfectly. 

# Test Machine

MacOS: Ventura 13.2.1
Firefox  Version:  110.0.1

# Steps to Reproduce 

1. Open FF and navigate to https://koboldplus.club/ 
2. Set party to 4 level 10 players, and include XP (or don't, whatever) 
3. Select Encounter Type 
4. Click the Roll button. 

On FF,  regardless of the number and level of players,  I always get just a small handfull of CR 1/8 monsters.   

![image](https://user-images.githubusercontent.com/124171/225138483-1ace2e62-df0d-4ef8-80a2-514abbb78883.png)

**Comment by V13Axel** [comment]
We've made some improvements and changes over the last few months that appear to have fixed this, at least when I try in Firefox on my end. That said, let us know if you're still seeing it! Happy to take a closer look.
