### ISSUE TITLE
Issues with Importing Custom/Third Party content

### ISSUE THREAD

**Issue by AraKentaurus** [fantasycalendar/kobold-plus-fight-club#28]
So I am using K+FC to generate encounters but after making a google sheet and trying to upload, I get this error [ "The caller does not have permission" ] and when trying creating a CSV file an importing that with the source CSV as well I get a good preview showing my list but then I import it. the import screen sticks and doesn't confirm or anything. If I click the import button again it says the sources are already imported but when I turn the source on, nothing shows up even when inputting tags. I tried this with another sheet someone else made and same result. After figuring out to make the google sheet public, I tried again and this error was returned to me ["Requested entity was not found."]

**Comment by V13Axel** [comment]
Hi there, I think this was fixed with the release of 2.3.3 last month, can you confirm @AraKentaurus ?
