### ISSUE TITLE
Source Importing Silently Fails

### ISSUE THREAD

**Issue by braedonwatkins** [fantasycalendar/kobold-plus-fight-club#29]
When attempting to upload via JSON (raw or file) and I click "Looks Good, Import Them!" the only things that happen is an error in the console and the sources disappear. Attempting to try again nets an error that the sources exist. The monsters do not seem to populate. 

Tried clearing my localStorage in case that was messing with it but didn't seem to change anything.

What's weird is this seemed to work for me ~1-2months ago.

**Comment by braedonwatkins** [comment]
Cloned the repo and gave it a closer look. Seems like there's something in the source importing that ingests the sources but fails silently. 

If you attempt to upload again it errors as sources already exist because... they do, technically.  Gonna try to turn this into a PR real quick if I can figure it out.

**Comment by braedonwatkins** [comment]
Wrote PR #30 for this

**Comment by Haxxer** [comment]
Could you please upload your json files? I appreciate your PR but I think it inherently addresses the wrong issue

**Comment by braedonwatkins** [comment]
No problem. I agree in that I'm probably only addressing a symptom and not the cause in the PR since I didn't want to get *too* lost in the codebase. I'm not used to Vue either so it was an interesting time 😅

I was able to get this behavior from the example JSON with a different custom source name but this is the original I discovered the problem with just for accuracy:

`{
    "sources": [
        {
            "name": "Custom Source 1",
            "type": "Custom",
            "shortname": "CS",
            "link": "https://homebrewery.naturalcrit.com/edit/savZmyJwkMDw"
        },
        {
            "name": "Another Custom Source",
            "type": "Third-Party",
            "shortname": "ACS",
            "link": "https://google.com/"
        }
    ],
    "monsters": [
        {
            "name": "Silas, The Disciple",
            "cr": "2",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "lawful evil",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 13,
            "hp": 19,
            "init": 2,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        },
        {
            "name": "Caelynn, The Fey-Touched",
            "cr": "2",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "chaotic evil",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 14,
            "hp": 23,
            "init": 3,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        },
        {
            "name": "Korag, The Beast",
            "cr": "2",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "chaotic neutral",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 14,
            "hp": 33,
            "init": 1,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        },
        {
            "name": "Zorath, The Witcher",
            "cr": "2",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "lawful neutral",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 17,
            "hp": 26,
            "init": 1,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        },
        {
            "name": "Redcloak Thief",
            "cr": "1",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "neutral evil",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 13,
            "hp": 18,
            "init": 3,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        },
        {
            "name": "Redcloak Archer",
            "cr": "1",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "neutral evil",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 14,
            "hp": 20,
            "init": 3,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        },
        {
            "name": "Redcloak Knight",
            "cr": "1",
            "size": "Medium",
            "type": "Humanoid",
            "tags": "Redcloaks",
            "section": "Bandits",
            "alignment": "neutral evil",
            "environment": "aquatic, arctic, cave, coast, desert, dungeon, forest, grassland, mountain, ruins, swamp, underground, urban",
            "ac": 16,
            "hp": 25,
            "init": 0,
            "lair": "",
            "legendary": "",
            "unique": "",
            "sources": "Custom Source: 2"
        }
    ]
}
`

**Comment by braedonwatkins** [comment]
Kinda wild to me I can't upload a JSON file directly as a comment of all places in GitHub 😭

**Comment by Haxxer** [comment]
One of your monsters are referencing `Custom Source`, while your sources contain `Custom Source 1` and `Another Custom Source` - they need to reference the name of the source exactly

**Comment by braedonwatkins** [comment]
Ah. I feel stupid. Sorry lol. 

If you think it's worth it I could change this to an issue on validating that monsters and sources have the same name on upload so another bonehead like me doesn't do this by accident. On a failure could give some feedback like `ay yo those monsters need the same source!` bc I didn't realize the uploader would take the source but not the monsters on an upload due to mismatching source names. 

If there isn't a use case for uploading partially like this from JSON maybe we could just fill the monster with the sources specified?

**Comment by Haxxer** [comment]
Yep, I think I'll patch that when I get the opportunity. Thanks for highlighting this issue!

**Comment by Haxxer** [comment]
https://github.com/fantasycalendar/kobold-plus-fight-club/pull/31 fixes this, I believe - it will at least tell you which monster is broken

**Comment by Haxxer** [comment]
![Screen Shot 2023-09-15 at 19 40 03](https://github.com/fantasycalendar/kobold-plus-fight-club/assets/12858387/58109feb-27b5-4d96-8b3c-a603bc6966b5)

**Comment by braedonwatkins** [comment]
Couldn't have done it better meself! Cool stuff!
