### ISSUE TITLE
Suggestion: Mouseover info for monsters in left-column encounter creator

### ISSUE THREAD

**Issue by Orthio** [fantasycalendar/kobold-plus-fight-club#43]
Would it be possible to give the same mouseover info available when looking up a monsters to the encounter design column on the left?

For example the info below is really useful. Being able to lookup the book and page that a troll is on.
![Troll Screenshot 2](https://github.com/fantasycalendar/kobold-plus-fight-club/assets/148891912/b62d7ed7-7755-4834-b19a-4b71a7810936)

But the same info isn't there when you select the troll to put it into an encounter.
So if I save the encounter and go back to it, I can't see the info for which book or page to find the troll monster, I'd have to search for troll again to get into it.
![Troll Screenshot 1](https://github.com/fantasycalendar/kobold-plus-fight-club/assets/148891912/12cdc813-f58f-4739-b658-41d67ac39ee8)

Thanks for all the work!

**Comment by Haxxer** [comment]
The book in the troll's name opens a dialog, isn't that what you need? 
![image](https://github.com/fantasycalendar/kobold-plus-fight-club/assets/12858387/2efd09be-e599-4408-96e3-7808fac14689)

**Comment by Orthio** [comment]
Ahh that is exactly what I need! It looks really similar to the save icon so I thought it was the same.

I guess that's case closed then actually, thanks for that
