### ISSUE TITLE
Pagination skips monsters

### ISSUE THREAD

**Issue by macdhollister** [fantasycalendar/kobold-plus-fight-club#8]
The list of monsters skips one monster after the first page.

Example with no filters:
First, with 25 per page, we can see the 11th result is "Frog" and the 12th result is "Giant Fire Beetle"
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/19469633/172987028-7d7ccc5f-fca5-4c9a-9333-1e03e2b2cc43.png">

When we go down to 10 per page, the first result of the second page skips "Frog" and starts with "Giant Fire Beetle"
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19469633/172987119-9eb7488a-4bf1-4cec-b472-033796a0fcd6.png">

**Comment by RodneyRichardson** [comment]
I don't see the same problem. On Windows 10 with Chrome v102.0.5005.63 64-bit, I see Frog on the second page (sorting by CR).
![image](https://user-images.githubusercontent.com/4490952/174992141-17e5cd03-a53a-4b72-9552-f9a5349817ff.png)

**Comment by macdhollister** [comment]
Apologies, I didn't include what browser I was using. I'm using Chrome Version 102.0.5005.61 (Official Build) (x86_64) on OSX 11.3. However, the issue appears to be gone now. I checked again and it appears a new monster "Cranium Rat" was added since I posted this issue, so the 10th, 11th, and 12th monsters respectively (when filtering to 25/page) are Deer, Eagle, and Frog. When filtering to 10/page, Eagle is the expected first result.

However that would imply that [RodneyRichardson](https://github.com/RodneyRichardson)'s results are incorrect, unless Cranium Rat was added within the past few hours.

**Comment by Haxxer** [comment]
It could just mean that you have a different set of sources active. In any case, do we feel confident enough that this has been fixed?

**Comment by V13Axel** [comment]
This was actually resolved in the process of porting to Vue.js. Should be all good now. :slightly_smiling_face:

**Comment by macdhollister** [comment]
Awesome! This issue seems resolved from what I can tell, although [Haxxer](https://github.com/Haxxer)'s comment did lead me to discovering another weird issue with sorting when applying different sources. 

When no filters were applied, only "official" sources not including "official adventure" were active, and sorted by ascending CR (after previously sorting on name, not sure if that matters), activating "official adventure" sources sent a few monsters to the end of the CR-0 section of the results (e.g. Cranium Rat was the last CR-0 result before CR-1/8 results began -- there are a few other monsters that seem out of place at the end of the CR-0 section, which is otherwise sorted alphabetically). I can make a separate issue so this one can be closed if that would be preferable.
