### ISSUE TITLE
Add Links from monster name to 5eTools

### ISSUE THREAD

**Issue by StevenACoffman** [fantasycalendar/kobold-plus-fight-club#9]
If I have added a monster in my encounter, it would be nice if the title of the monster is linked to the 5etools stat block for easy printing. For instance, an Aarakockra from the Monster Manual is:
https://5e.tools/bestiary.html#aarakocra_mm

The pattern is "https://5e.tools/bestiary.html#" + monster + "_" + source

**Comment by Haxxer** [comment]
As 5e.tools contains copyrighted content, we cannot link to it in any fashion.

Closing ticket.
